### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by thomastuts** [thomastuts/tome-api#1]
# MVP
- [ ] Automatic scraping for existing feeds
- [ ] Automatic scraping for newly added feed
- [ ] Progress bar with socket.io for new feed import
- [ ] Highlight text & save notes

# Future
- [ ] User curated collections
